

CAMPO=TERMINAL, AUXILIAR, OCULTO, "__________________"

BEGINBLOQUE=VDUSUARIO.PAN
  PREREGISTRO=PRESEHIJO
  REGPAG=15
CAMPO=TERMINAL, AUXILIAR, VIRTUAL,OCULTO
ENDBLOQUE  
BEGINBLOQUE=VDASIUSUGRU.PAN
  PADRE=VDUSUARIO.PAN
  POSY=21
  REGPAG=20
ENDBLOQUE  
BEGINBLOQUE=VDASIUSUPRI.PAN
  PADRE=VDUSUARIO.PAN
  POSY=21
  POSX=58
  REGPAG=20
ENDBLOQUE  