BEGINBLOQUE=VDTRANSFORMASTK1.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
  NOLOCK
ENDBLOQUE  
BEGINBLOQUE=VDTRANSFORMASTK2.PAN
  PADRE=VDTRANSFORMASTK1.PAN
  POSX=1
  POSY=33
  NOLOCK
ENDBLOQUE  

