CAMPO=CODCOMEN,AUXILIAR,OCULTO,"@L@@@@@@@@@@@"
BEGINBLOQUE=VDTIPOCOMEN.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
  REGPAG=12
  CAMPO=CODCOMEN,VIRTUAL,AUXILIAR,OCULTO
ENDBLOQUE  
BEGINBLOQUE=VDCOMEN1.PAN
  PADRE=VDTIPOCOMEN.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=18
  REGPAG=10
ENDBLOQUE  
#BEGINBLOQUE=VDCOMEN2.PAN
#  PADRE=VDCOMEN1.PAN
#  PREREGISTRO=PRESEHIJO
#  POSX=13
#  POSY=18
#  REGPAG=1
#ENDBLOQUE  


