INCLUDEFICHEROCSS="vertissimple.css"
BEGINBLOQUE=VDDEVOLDIVIS.PAN
  PREREGISTRO=PRESEHIJO
  REGPAG=1
  WLONY=550
  WLONX=850
  
ENDBLOQUE
BEGINBLOQUE=VDCAUSADEVOL.PAN
  PADRE=VDDEVOLDIVIS.PAN
  PREQUERY=QUERYHIJO
  WMARCOFRAME
  WLONX=820
  POSY=20
  POSX=2
ENDBLOQUE    