SELECCION DE ARTICULO/LOTE
Div   Articulo              Designacion           Lote
_20__ _40__________________ _100_________________ _40______________
|
INCLUDEFICHEROCSS="vertissimple.css"
REGPAG=40
ORDERBY=CODART,CODLOT;
SOLOQUERY
SELECT=SELECT AR.CODART,AR.CODDIV,AR.DESART,LO.CODLOT
        FROM VDARTIC AR,VDLOTES LO
        WHERE AR.CODART=LO.CODART;
CAMPO=CODDIV,TITULO("Div")
CAMPO=CODART,TITULO("Artículo")
CAMPO=DESART
CAMPO=CODLOT,TITULO("Lote")

