#Form de monitorización de bloqueos
BEGINBLOQUE=VDORAERR.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
  REGPAG=23
  PQUERY
ENDBLOQUE
BEGINBLOQUE=VDORAERR2.PAN
  PADRE=VDORAERR.PAN
  REGPAG=1
  POSX=1
  POSY=28
ENDBLOQUE

