MONITOR DE EXTENSIONES DE TABLAS E INDICES

 Extend-id   Block-id   Blocks       Bytes
 @L@@@@@@@  @L@@@@@@@  @L@,@@@@@  #L####,#######
|

SOLOQUERY
SELECT=SELECT EXTENT_ID,BLOCK_ID,BLOCKS,BYTES
       FROM SYS.DBA_EXTENTS;
ORDERBY=1,2;       

CAMPO=OWNER,VIRTUAL,OCULTO
CAMPO=SEGMENT_NAME,VIRTUAL,OCULTO
CAMPO=SEGMENT_TYPE,VIRTUAL,OCULTO
CAMPO=TABLESPACE_NAME,VIRTUAL,OCULTO
CAMPO=FILE_ID,VIRTUAL,OCULTO
CAMPO=EXTENT_ID
CAMPO=BLOCK_ID
CAMPO=BLOCKS
CAMPO=BYTES
