BEGINBLOQUE=VDGRAFICA.PAN
  PREREGISTRO=PRESEHIJO
  POSX=0
  POSY=1
  REGPAG=15
ENDBLOQUE

BEGINBLOQUE=VDGRAFICAEJE.PAN
  PADRE=VDGRAFICA.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=20
  REGPAG=1
ENDBLOQUE
BEGINBLOQUE=VDGRAFICASERIE.PAN
  PADRE=VDGRAFICA.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=33
ENDBLOQUE
BEGINBLOQUE=VDGRAFICAPIE.PAN
  PADRE=VDGRAFICA.PAN
  PREREGISTRO=PRESEHIJO
  POSX=123
  POSY=1
  REGPAG=25
ENDBLOQUE

