BEGINBLOQUE=VDDEFCAMPO.PAN
 PREREGISTRO=PRESEHIJO
 POSX=1
 POSY=1
 REGPAG=38
ENDBLOQUE
BEGINBLOQUE=VDDEFCAMPODET.PAN
 PADRE=VDDEFCAMPO.PAN
 PREREGISTRO=PRESEHIJO
 POSY=44
 POSX=1
 REGPAG=1
ENDBLOQUE

