BEGINBLOQUE=VDDEFGRUPOBLOQUE.PAN
 PREREGISTRO=PRESEHIJO
 POSX=1
 POSY=1
 REGPAG=10
 AYUDA=CARACTERISTICAS POR DEFECTO DE PANTALLAS
ENDBLOQUE
BEGINBLOQUE=VDDEFBLOQUE.PAN
 PADRE=VDDEFGRUPOBLOQUE.PAN
 PREREGISTRO=PRESEHIJO
 CAMPO=GRUPOBLOQUEAUX,AUXILIAR,VIRTUAL("GRUPOBLOQUE"),OCULTO
 WHERE=GRUPOBLOQUE LIKE :GRUPOBLOQUEAUX;
 POSX=1
 POSY=16
 REGPAG=23
ENDBLOQUE
BEGINBLOQUE=VDDEFBLOQUEDET.PAN
 PADRE=VDDEFBLOQUE.PAN
 PREREGISTRO=PRESEHIJO
 POSY=43
 POSX=1
 REGPAG=1
ENDBLOQUE

