CAMPO=ROWIDHIST,AUXILIAR,OCULTO,"_40"
CAMPO=MITABLA,AUXILIAR,OCULTO,"_40"
BEGINBLOQUE=VDDIFAUD.PAN
  PREQUERY=FEJECUTA("CSELTABLA","")
  CURSOR=CSELTABLA SELECT VD.DAMETABLAROWID(:ROWIDHIST) MITABLA FROM DUAL;
  REGPAG=40
ENDBLOQUE