CAMPO=MITABLA,AUXILIAR,OCULTO,"_40"
CAMPO=ROWIDHIST,AUXILIAR,OCULTO,"_40"
BEGINBLOQUE=VDGEN$AUD.PAN
  PQUERY
  PREQUERY=FEJECUTA("CSELTABLA","")
  CAMPO=MITABLA,AUXILIAR,VIRTUAL,OCULTO
  CURSOR=CSELTABLA SELECT VD.DAMETABLAROWID(:ROWIDHIST) MITABLA FROM DUAL;
  PREREGISTRO=PRESEHIJO
ENDBLOQUE
BEGINBLOQUE=VDDIFAUD.PAN
  CAMPO=ROWIDAUX,AUXILIAR,VIRTUAL("MIROWID"),OCULTO
  PREQUERY=QUERYHIJO
  PADRE=VDGEN$AUD.PAN
  WHERE=MIROWID=:ROWIDAUX;
  POSY=30
  REGPAG=20
ENDBLOQUE