BEGINBLOQUE=VDGRUPOPROP.PAN
  PREREGISTRO=PRESEHIJO
  REGPAG=20
ENDBLOQUE  

BEGINBLOQUE=VDINSTPROP.PAN
  PADRE=VDGRUPOPROP.PAN
  PREQUERY=QUERYHIJO
  PREREGISTRO=PRESEHIJO
  REGPAG=3
  POSY=26
ENDBLOQUE  

BEGINBLOQUE=VDCONFI.PAN
  PADRE=VDINSTPROP.PAN
  PREQUERY=QUERYHIJO
  POSY=33
  REGPAG=20
ENDBLOQUE  