BEGINBLOQUE=VDMODULOS.PAN
    PREREGISTRO=PRESEHIJO
    REGPAG=10
ENDBLOQUE   

BEGINBLOQUE=VDMENSAJES.PAN
    PREQUERY=QUERYHIJO
    PADRE=VDMODULOS.PAN
    REGPAG=35
    POSY=16
ENDBLOQUE     