BEGINBLOQUE=VDPEDCABMISC.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
ENDBLOQUE  
BEGINBLOQUE=VDPEDLINMISC.PAN
  PADRE=VDPEDCABMISC.PAN
#  PREQUERY=QUERYHIJO
  POSX=1
  POSY=43
  REGPAG=10
ENDBLOQUE  