BEGINBLOQUE=VDARTESPSTOCK1.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
  REGPAG=25 
ENDBLOQUE  
BEGINBLOQUE=VDLISTAMOV.PAN
  PADRE=VDARTESPSTOCK1.PAN
  CAMPO=CODARTAUX,AUXILIAR,VIRTUAL("CODART"),OCULTO
  WHERE= CODART=:CODARTAUX AND NVL(CODDEMANDA,0)=0 AND STATUS<VDST.FMOVRECOGIDO;
  ORDERBY= STATUS DESC,CODMOV;
  TITULO=MOVIMIENTOS PENDIENTES DEL ARTICULO
  PREQUERY=QUERYHIJO
  POSX=1
  POSY=31
  REGPAG=11
ENDBLOQUE  