BEGINBLOQUE=VDRECURSOSTAREASPEND.PAN
  PREREGISTRO=PRESEHIJO
   REGPAG=10
ENDBLOQUE

BEGINBLOQUE=VDRECMOVIM.PAN
 PADRE=VDRECURSOSTAREASPEND.PAN
 PREQUERY=QUERYHIJO
 REGPAG=20
 POSY=16
ENDBLOQUE