BEGINBLOQUE=VDBULCABPINV.PAN
  PREREGISTRO=PRESEHIJO
  CAMPO=CODMATAUX,AUXILIAR,OCULTO,"_18_______" 
  NOUPDATE
  NOINSERT
  NODELETE
  POSTQUERY=FEJECUTA("CCODMATAUX","")
  REGPAG=1
  CURSOR=CCODMATAUX SELECT :CODMAT CODMATAUX FROM DUAL;
ENDBLOQUE
BEGINBLOQUE=VDLISTAMOV.PAN
  PREQUERY=QUERYHIJO
  CAMPO=CODMATAUX,AUXILIAR,VIRTUAL,OCULTO
  WHERE= (:CODMATAUX = CODMATORI OR :CODMATAUX=CODMATDEST);
  ORDERBY= CODMOV DESC;
  PADRE=VDBULCABPINV.PAN
  POSY=16
  REGPAG=30
ENDBLOQUE  