BEGINBLOQUE=VDCALIF.PAN
  PREREGISTRO=PRESEHIJO
  REGPAG=10
ENDBLOQUE
BEGINBLOQUE=VDCALIFVALOR.PAN
  PADRE=VDCALIF.PAN
  PREQUERY=QUERYHIJO
  REGPAG=10
  POSY=16
ENDBLOQUE
BEGINBLOQUE=VDCALIFPRIV.PAN
  PADRE=VDCALIF.PAN
  PREQUERY=QUERYHIJO
  REGPAG=10
  POSY=30
  POSX=1
ENDBLOQUE
  