BEGINBLOQUE=VDLOTESHIST.PAN
  PREREGISTRO=PRESEHIJO
  REGPAG=30
  POSY=2
ENDBLOQUE
BEGINBLOQUE=VDLOTESHIST2.PAN
  PADRE=VDLOTESHIST.PAN
  PREQUERY=QUERYHIJO
  POSY=36
  REGPAG=1
ENDBLOQUE    
  