OPTIMOS AREA
Area        Maximo Minimo Urg.   Un
_40________ @L,@@@ @L,@@@ @L,@@@ _10___
|
TABLA=VDOPTIMOAREAARTIC
REGPAG=5

CAMPO=CODART,VIRTUAL,OCULTO
CAMPO=CODAREA,NOUPDATE
CAMPO=STKMAX
CAMPO=STKMIN
CAMPO=STKURG
CAMPO=UNIRECARGA