
CAMPO=PROCESO, OCULTO, "_32_"
CAMPO=FUNCION, OCULTO, "_32_"
CAMPO=TIPOPROC,OCULTO,"_"

BEGINBLOQUE=VDPARAMALGPROC.PAN
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=1
 POSY=1
ENDBLOQUE