######
# VDPROCESOS.FRM - Sistema de ventanas de configuración de algoritmos.
# 
# PropOsito: Form de ventanas para la creación/modificación de los datos sobre
#            configuración de procesos en V10.   
#           
# Autor	   : PACO
# Fecha    : 07-02-2008
####
# Modificaciones:
####
BEGINBLOQUE=VDPROCESOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=1
 POSY=1
 REGPAG=9
ENDBLOQUE

BEGINBLOQUE=VDPARAMETROS.PAN
 PADRE=VDPROCESOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=92
 POSY=1
 REGPAG=10
ENDBLOQUE

BEGINBLOQUE=VDALGORITMOS.PAN
 PADRE=VDPROCESOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=1
 POSY=16
 REGPAG=10
ENDBLOQUE

BEGINBLOQUE=VDDISCALGORITMOS.PAN
 PADRE=VDALGORITMOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=1
 POSY=30
 REGPAG=8
ENDBLOQUE

BEGINBLOQUE=VDPARAMALGORITMOS.PAN
 PADRE=VDALGORITMOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=61
 POSY=30
 REGPAG=8
ENDBLOQUE

BEGINBLOQUE=VDPREPOSTALGORITMOS.PAN
 PADRE=VDALGORITMOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=1
 POSY=42
 REGPAG=7
ENDBLOQUE


BEGINBLOQUE=VDPARAMPREPOSTALG.PAN
 PADRE=VDPREPOSTALGORITMOS.PAN
 PREREGISTRO=PRESEHIJO
 NOINSERT,PROTECT("SUPERVISOR")
 NODELETE,PROTECT("SUPERVISOR")
 NOUPDATE,PROTECT("SUPERVISOR")
 POSX=102
 POSY=42
 REGPAG=7
ENDBLOQUE


