BEGINBLOQUE=VDINFOLECTURAS.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
  REGPAG=20
ENDBLOQUE
BEGINBLOQUE=VDORDENADORES.PAN
  PADRE= VDINFOLECTURAS.PAN
  POSX=1
  POSY=26
  REGPAG=10
ENDBLOQUE

