BEGINBLOQUE=VDPEDCAB.PAN
  PREREGISTRO=PRESEHIJO
  POSX=1
  POSY=1
  WHERE=TIPODEMANDA='DEMPEDIDO';
  ORDERBY=STATUS,CODPED;
#  NOUPDATE
#  NODELETE
#  NOINSERT
ENDBLOQUE  
BEGINBLOQUE=VDPEDLIN.PAN
  PADRE=VDPEDCAB.PAN
  WDESPLEGADO   
  PREQUERY=QUERYHIJO
  POSX=1
  POSY=46
  REGPAG=10
  NOUPDATE
  NODELETE
  NOINSERT
ENDBLOQUE  