CAMPO=POSICION,OCULTO,AUXILIAR,OCULTO,"#L#"
CAMPO=BLOQUEOACTUAL,AUXILIAR,OCULTO,"_"
CAMPO=NUEVOBLOQUEO,AUXILIAR,OCULTO,"_"
CAMPO=TIPOACCION,AUXILIAR,OCULTO,"_50________"
CAMPO=LITERAL,AUXILIAR,OCULTO,"_100"
CAMPO=VALIDA,AUXILIAR,OCULTO,"_"
BEGINBLOQUE=VDLIBUNLOTE.PAN
ENDBLOQUE   